org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.23
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

## Mod Properties
mod_id=infinitygauntlet
mod_name=Infinity Gauntlet Mod
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.minhphuc.infinitygauntlet
mod_authors=MinhPhuc00ne
mod_description=Mod Găng Tay Vô Cực cho Minecraft 1.20.1 Forge với tính năng Búng tay 100 blocks, chọn viên đá qua phím PgUp và tối ưu hóa đa luồng Async.