modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="darkgathering"
version="1.0.0"
displayName="Dark Gathering"
authors="MinhPhuc00ne"
description='''
Dark Gathering Mod inspired by the manga/anime series.
'''

[[dependencies.darkgathering]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.darkgathering]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1, 1.21)"
    ordering="NONE"
    side="BOTH"
