modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="backrooms"
version="1.0.0"
displayName="The Backrooms Mod"
authors="MinhPhuc00ne"
description='''
Mod The Backrooms cho Minecraft 1.20.1 Forge.
Kham pha chieu khong gian Level 0, tuong giay vang, den huynh quang vo ve va sinh ton bang Nuoc Hanh Nhan!
'''

[[dependencies.backrooms]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.backrooms]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1, 1.21)"
    ordering="NONE"
    side="BOTH"
